{
 "title": "Solr Dashboard",
 "description": "Solr Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "zk_host",
    "query": "label_values(solr_ping{zk_host=~\".+\"},zk_host)"
   },
   {
    "name": "base_url",
    "query": "label_values(solr_ping{base_url=~\".+\"},base_url)"
   },
   {
    "name": "collection",
    "query": "label_values(solr_collections_shard_state{zk_host=~\"$zk_host\",collection=~\".+\"},collection)"
   },
   {
    "name": "shard",
    "query": "label_values(solr_collections_shard_state{zk_host=~\"$zk_host\",collection=~\"$collection\",shard=~\".+\"},shard)"
   },
   {
    "name": "replica",
    "query": "label_values(solr_collections_replica_state{zk_host=~\"$zk_host\",collection=~\"$collection\",shard=~\"$shard\",replica=~\".+\"},replica)"
   },
   {
    "name": "core",
    "query": "label_values(solr_collections_replica_state{zk_host=~\"$zk_host\",collection=~\"$collection\",shard=~\"$shard\",replica=~\"$replica\"},core)"
   },
   {
    "name": "searchHandler",
    "query": "label_values(solr_metrics_core_query_errors_1minRate{zk_host=~\"$zk_host\",collection=~\"$collection\",shard=~\"$shard\",replica=~\"$replica\"},searchHandler)"
   }
  ]
 },
 "panels": [
  { "title": "Query Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total QPS (by collection)",
   "type": "graph",
   "description": "Distributed QPS 1-min rate  aggregated by collection, roughly the current QPS across all nodes per collection",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "qps" }
   ],
   "targets": [
    {
     "expr": "sum by (collection) (solr_metrics_core_query_1minRate{base_url=~\"$base_url\",collection=~\"$collection\",shard=~\"$shard\",replica=~\"$replica\",core=~\"$core\",searchHandler=~\"$searchHandler\"})",
     "legendFormat": "{{collection}}"
    }
   ]
  },
  {
   "title": "Total QPS (by node)",
   "type": "graph",
   "description": "Distributed QPS 1-min rate aggregated by base_url (Solr node)",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (base_url) (solr_metrics_core_query_1minRate{base_url=~\"$base_url\",collection=~\"$collection\",shard=~\"$shard\",replica=~\"$replica\",core=~\"$core\",searchHandler=~\"$searchHandler\"})",
     "legendFormat": "{{base_url}}"
    }
   ]
  },
  {
   "title": "Distributed QPS per Core (1-min rate)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "qps" }
   ],
   "targets": [
    {
     "expr": "solr_metrics_core_query_1minRate{base_url=~\"$base_url\",collection=~\"$collection\",shard=~\"$shard\",replica=~\"$replica\",core=~\"$core\",searchHandler=~\"$searchHandler\"}",
     "legendFormat": "{{base_url}}  {{core}}  {{searchHandler}}"
    }
   ]
  },
  {
   "title": "Distributed QPS per Core (5-min rate)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "solr_metrics_core_query_5minRate{base_url=~\"$base_url\",collection=~\"$collection\",shard=~\"$shard\",replica=~\"$replica\",core=~\"$core\",searchHandler=~\"$searchHandler\"}",
     "legendFormat": "{{base_url}}  {{core}}  {{searchHandler}}"
    }
   ]
  },
  {
   "title": "Distributed Query Time per Core (p99 ms)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 8 },
   "yaxes": [
    { "format": "short", "label": "ms" }
   ],
   "targets": [
    {
     "expr": "solr_metrics_core_query_p99_ms{base_url=~\"$base_url\",collection=~\"$collection\",shard=~\"$shard\",replica=~\"$replica\",core=~\"$core\",searchHandler=~\"$searchHandler\"}",
     "legendFormat": "{{base_url}}  {{core}}  {{searchHandler}}"
    }
   ]
  },
  {
   "title": "Distributed Query Time per Core (p95 ms)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "solr_metrics_core_query_p95_ms{base_url=~\"$base_url\",collection=~\"$collection\",shard=~\"$shard\",replica=~\"$replica\",core=~\"$core\",searchHandler=~\"$searchHandler\"}",
     "legendFormat": "{{base_url}}  {{core}}  {{searchHandler}}"
    }
   ]
  },
  {
   "title": "Distributed Query Time per Core (p75 ms)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "solr_metrics_core_query_p75_ms{base_url=~\"$base_url\",collection=~\"$collection\",shard=~\"$shard\",replica=~\"$replica\",core=~\"$core\",searchHandler=~\"$searchHandler\"}",
     "legendFormat": "{{base_url}}  {{core}}  {{searchHandler}}"
    }
   ]
  },
  {
   "title": "Local Query Count per Core",
   "type": "graph",
   "description": "Helps identify if a core is receiving more traffic than other cores, possibly indicating unbalanced load.",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 15 },
   "yaxes": [
    { "format": "short", "label": "qps" }
   ],
   "targets": [
    {
     "expr": "increase(solr_metrics_core_query_local_count{base_url=~\"$base_url\",collection=~\"$collection\",shard=~\"$shard\",replica=~\"$replica\",core=~\"$core\",searchHandler=~\"$searchHandler\"}[1m])",
     "legendFormat": "{{base_url}}/{{core}}{{searchHandler}}"
    }
   ]
  },
  {
   "title": "Local QPS per Core (1-min rate)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 15 },
   "yaxes": [
    { "format": "short", "label": "qps" }
   ],
   "targets": [
    {
     "expr": "solr_metrics_core_query_local_1minRate{base_url=~\"$base_url\",collection=~\"$collection\",shard=~\"$shard\",replica=~\"$replica\",core=~\"$core\",searchHandler=~\"$searchHandler\"}",
     "legendFormat": "{{base_url}}/{{core}}{{searchHandler}}"
    }
   ]
  },
  {
   "title": "Local Query Time per Core (p95 ms)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "solr_metrics_core_query_local_p95_ms{base_url=~\"$base_url\",collection=~\"$collection\",shard=~\"$shard\",replica=~\"$replica\",core=~\"$core\",searchHandler=~\"$searchHandler\"}",
     "legendFormat": "{{base_url}}/{{core}}{{searchHandler}}"
    }
   ]
  },
  {
   "title": "Query Client Errors per Core (1-min rate)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "solr_metrics_core_query_client_errors_1minRate{base_url=~\"$base_url\",collection=~\"$collection\",shard=~\"$shard\",replica=~\"$replica\",core=~\"$core\",searchHandler=~\"$searchHandler\"}",
     "legendFormat": "{{base_url}}  {{core}}  {{searchHandler}}"
    }
   ]
  },
  {
   "title": "Query Errors per Core (1-min rate)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "solr_metrics_core_query_errors_1minRate{base_url=~\"$base_url\",collection=~\"$collection\",shard=~\"$shard\",replica=~\"$replica\",core=~\"$core\",searchHandler=~\"$searchHandler\"}",
     "legendFormat": "{{base_url}}  {{core}}  {{searchHandler}}"
    }
   ]
  },
  { "title": "Jetty Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "Requests",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(solr_metrics_jetty_requests_total{base_url=~\"$base_url\"}[1m])",
     "legendFormat": "{{base_url}} {{method}}"
    }
   ]
  },
  {
   "title": "Response",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(solr_metrics_jetty_response_total{base_url=~\"$base_url\"}[1m])",
     "legendFormat": "{{base_url}} {{status}}"
    }
   ]
  },
  {
   "title": "Dispatches",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(solr_metrics_jetty_dispatches_total{base_url=~\"$base_url\"}[1m])",
     "legendFormat": "{{base_url}}"
    }
   ]
  },
  { "title": "JVM Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 } },
  {
   "title": "Buffers",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "solr_metrics_jvm_buffers{base_url=~\"$base_url\"}",
     "legendFormat": "{{base_url}} {{pool}}"
    }
   ]
  },
  {
   "title": "Buffer Size",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 45 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "solr_metrics_jvm_buffers_bytes{base_url=~\"$base_url\"}",
     "legendFormat": "{{base_url}} {{pool}} {{item}}"
    }
   ]
  },
  {
   "title": "GC Count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 52 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(solr_metrics_jvm_gc_total{base_url=~\"$base_url\"}[1m])",
     "legendFormat": "{{base_url}} {{item}}"
    }
   ]
  },
  {
   "title": "GC Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 52 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "increase(solr_metrics_jvm_gc_seconds_total{base_url=~\"$base_url\"}[1m])",
     "legendFormat": "{{base_url}} {{item}}"
    }
   ]
  },
  {
   "title": "Heap Size",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 59 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "solr_metrics_jvm_memory_heap_bytes{base_url=~\"$base_url\"}",
     "legendFormat": "{{base_url}} {{item}}"
    }
   ]
  },
  {
   "title": "Non-Heap Size",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 59 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "solr_metrics_jvm_memory_non_heap_bytes{base_url=~\"$base_url\"}",
     "legendFormat": "{{base_url}} {{item}}"
    }
   ]
  },
  {
   "title": "Pool Size",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 66 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "solr_metrics_jvm_memory_pools_bytes{base_url=~\"$base_url\"}",
     "legendFormat": "{{base_url}} {{space}} {{item}}"
    }
   ]
  },
  {
   "title": "Memory Size",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 66 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "solr_metrics_jvm_memory_bytes{base_url=~\"$base_url\"}",
     "legendFormat": "{{base_url}} {{item}}"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 73 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "solr_metrics_jvm_threads{base_url=~\"$base_url\"}",
     "legendFormat": "{{base_url}} {{item}}"
    }
   ]
  },
  { "title": "OS Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 80 } },
  {
   "title": "Memory Size",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 81 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "solr_metrics_jvm_os_memory_bytes{base_url=~\"$base_url\"}",
     "legendFormat": "{{base_url}} {{item}}"
    }
   ]
  },
  {
   "title": "File Descriptors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 81 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "solr_metrics_jvm_os_file_descriptors{base_url=~\"$base_url\"}",
     "legendFormat": "{{base_url}} {{item}}"
    }
   ]
  },
  {
   "title": "CPU Load",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 88 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "solr_metrics_jvm_os_cpu_load{base_url=~\"$base_url\"}",
     "legendFormat": "{{base_url}} {{item}}"
    }
   ]
  },
  {
   "title": "CPU Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 88 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(solr_metrics_jvm_os_cpu_time_seconds{base_url=~\"$base_url\"}[1m])",
     "legendFormat": "{{base_url}} {{item}}"
    }
   ]
  },
  {
   "title": "Load Average",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 95 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "solr_metrics_jvm_os_load_average{base_url=~\"$base_url\"}",
     "legendFormat": "{{base_url}} {{item}}"
    }
   ]
  },
  { "title": "Node Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 102 } },
  {
   "title": "Requests",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 103 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "solr_metrics_node_requests_total{base_url=~\"$base_url\"}",
     "legendFormat": "{{base_url}} {{handler}}"
    }
   ]
  },
  {
   "title": "Request Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 103 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(solr_metrics_node_time_seconds_total{base_url=~\"$base_url\"}[1m])",
     "legendFormat": "{{base_url}}{{handler}}"
    }
   ]
  },
  {
   "title": "Client Errors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 110 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(solr_metrics_node_client_errors_total{base_url=~\"$base_url\"}[1m])",
     "legendFormat": "{{base_url}}{{handler}}"
    }
   ]
  },
  {
   "title": "Server Errors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 110 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(solr_metrics_node_server_errors_total{base_url=~\"$base_url\"}[1m])",
     "legendFormat": "{{base_url}}{{handler}}"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 117 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(solr_metrics_node_errors_total{base_url=~\"$base_url\"}[1m])",
     "legendFormat": "{{base_url}}{{handler}}"
    }
   ]
  },
  {
   "title": "Timeouts",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 117 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(solr_metrics_node_timeouts_total{base_url=~\"$base_url\"}[1m])",
     "legendFormat": "{{base_url}}{{handler}}"
    }
   ]
  },
  {
   "title": "Cores",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 124 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "solr_metrics_node_cores{base_url=~\"$base_url\"}",
     "legendFormat": "{{base_url}} {{item}}"
    }
   ]
  },
  {
   "title": "Core Root File System",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 124 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "solr_metrics_node_core_root_fs_bytes{base_url=~\"$base_url\"}",
     "legendFormat": "{{base_url}} {{item}}"
    }
   ]
  },
  {
   "title": "Thread Pool Completed",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 131 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "solr_metrics_node_thread_pool_completed_total{base_url=~\"$base_url\"}",
     "legendFormat": "{{base_url}} {{handler}} {{executor}}"
    }
   ]
  },
  {
   "title": "Thread Pool Submitted",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 131 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "solr_metrics_node_thread_pool_submitted_total{base_url=~\"$base_url\"}",
     "legendFormat": "{{base_url}} {{handler}} {{executor}}"
    }
   ]
  },
  {
   "title": "Thread Pool Running",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 138 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "solr_metrics_node_thread_pool_running{base_url=~\"$base_url\"}",
     "legendFormat": "{{base_url}} {{handler}} {{executor}}"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 145 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "solr_metrics_node_connections{base_url=~\"$base_url\"}",
     "legendFormat": "{{base_url}} {{handler}} {{item}}"
    }
   ]
  },
  {
   "title": "Leader Count (by node)",
   "type": "graph",
   "description": "Number of leaders on each node",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 145 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (base_url) (solr_collections_shard_leader{base_url=~\"$base_url\",collection=~\"$collection\",shard=~\"$shard\",replica=~\"$replica\",core=~\"$core\"})",
     "legendFormat": "{{base_url}}"
    }
   ]
  },
  { "title": "Core Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 152 } },
  {
   "title": "Requests",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 153 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(solr_metrics_core_requests_total{base_url=~\"$base_url\",collection=~\"$collection\",shard=~\"$shard\",replica=~\"$replica\",core=~\"$core\"}[1m])",
     "legendFormat": "{{base_url}}/{{core}}{{handler}}"
    }
   ]
  },
  {
   "title": "Request Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 153 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(solr_metrics_core_time_seconds_total{base_url=~\"$base_url\",collection=~\"$collection\",shard=~\"$shard\",replica=~\"$replica\",core=~\"$core\"}[1m])",
     "legendFormat": "{{base_url}}/{{core}}{{handler}}"
    }
   ]
  },
  {
   "title": "Client Errors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 160 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(solr_metrics_core_client_errors_total{base_url=~\"$base_url\",collection=~\"$collection\",shard=~\"$shard\",replica=~\"$replica\",core=~\"$core\"}[1m])",
     "legendFormat": "{{base_url}}/{{core}}{{handler}}"
    }
   ]
  },
  {
   "title": "Server Errors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 160 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(solr_metrics_core_server_errors_total{base_url=~\"$base_url\",collection=~\"$collection\",shard=~\"$shard\",replica=~\"$replica\",core=~\"$core\"}[1m])",
     "legendFormat": "{{base_url}}/{{core}}{{handler}}"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 167 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(solr_metrics_core_errors_total{base_url=~\"$base_url\",collection=~\"$collection\",shard=~\"$shard\",replica=~\"$replica\",core=~\"$core\"}[1m])",
     "legendFormat": "{{base_url}}/{{core}}{{handler}}"
    }
   ]
  },
  {
   "title": "Timeouts",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 167 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(solr_metrics_core_timeouts_total{base_url=~\"$base_url\",collection=~\"$collection\",shard=~\"$shard\",replica=~\"$replica\",core=~\"$core\"}[1m])",
     "legendFormat": "{{base_url}}/{{core}}{{handler}}"
    }
   ]
  },
  {
   "title": "Searcher Cache Hit Ratio",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 174 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "solr_metrics_core_searcher_cache_ratio{base_url=~\"$base_url\",collection=~\"$collection\",shard=~\"$shard\",replica=~\"$replica\",core=~\"$core\"}",
     "legendFormat": "{{base_url}}/{{core}} {{type}} {{item}}"
    }
   ]
  },
  {
   "title": "Searcher Cache",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 174 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "solr_metrics_core_searcher_cache{base_url=~\"$base_url\",collection=~\"$collection\",shard=~\"$shard\",replica=~\"$replica\",core=~\"$core\"}",
     "legendFormat": "{{base_url}}/{{core}} {{type}} {{item}}"
    }
   ]
  },
  {
   "title": "Searcher Warm Up Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 181 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "solr_metrics_core_searcher_warmup_time_seconds{base_url=~\"$base_url\",collection=~\"$collection\",shard=~\"$shard\",replica=~\"$replica\",core=~\"$core\"}",
     "legendFormat": "{{base_url}}/{{core}} {{type}}"
    }
   ]
  },
  {
   "title": "Searcher Cumulative Cache",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 181 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(solr_metrics_core_searcher_cumulative_cache_total{base_url=~\"$base_url\",collection=~\"$collection\",shard=~\"$shard\",replica=~\"$replica\",core=~\"$core\"}[1m])",
     "legendFormat": "{{base_url}}/{{core}} {{type}} {{item}}"
    }
   ]
  },
  {
   "title": "File System",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 188 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "solr_metrics_core_fs_bytes{base_url=~\"$base_url\",collection=~\"$collection\",shard=~\"$shard\",replica=~\"$replica\",core=~\"$core\"}",
     "legendFormat": "{{base_url}}/{{core}}"
    }
   ]
  },
  {
   "title": "Index Size",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 188 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "solr_metrics_core_index_size_bytes{base_url=~\"$base_url\",collection=~\"$collection\",shard=~\"$shard\",replica=~\"$replica\",core=~\"$core\"}",
     "legendFormat": "{{base_url}}/{{core}}"
    }
   ]
  },
  {
   "title": "Searcher Documents",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 195 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "solr_metrics_core_searcher_documents{base_url=~\"$base_url\",collection=~\"$collection\",shard=~\"$shard\",replica=~\"$replica\",core=~\"$core\"}",
     "legendFormat": "{{base_url}}/{{core}} {{item}}"
    }
   ]
  },
  {
   "title": "Update Handler Adds (cumulative)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 202 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(solr_metrics_core_update_handler_adds_total{base_url=~\"$base_url\",collection=~\"$collection\",shard=~\"$shard\",replica=~\"$replica\",core=~\"$core\"}[1m])",
     "legendFormat": "{{base_url}}/{{core}}"
    }
   ]
  },
  {
   "title": "Pending Docs",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 202 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "solr_metrics_core_update_handler_pending_docs{base_url=~\"$base_url\",collection=~\"$collection\",shard=~\"$shard\",replica=~\"$replica\",core=~\"$core\"}",
     "legendFormat": "{{base_url}}/{{core}}"
    }
   ]
  },
  {
   "title": "Update Handler Deletes By ID",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 209 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(solr_metrics_core_update_handler_deletes_by_id_total{base_url=~\"$base_url\",collection=~\"$collection\",shard=~\"$shard\",replica=~\"$replica\",core=~\"$core\"}[1m])",
     "legendFormat": "{{base_url}}/{{core}}"
    }
   ]
  },
  {
   "title": "Update Handler Deletes By Query",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 209 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(solr_metrics_core_update_handler_deletes_by_query_total{base_url=~\"$base_url\",collection=~\"$collection\",shard=~\"$shard\",replica=~\"$replica\",core=~\"$core\"}[1m])",
     "legendFormat": "{{base_url}}/{{core}}"
    }
   ]
  },
  {
   "title": "Update Handler Expunge Deletes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 209 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(solr_metrics_core_update_handler_expunge_deletes_total{base_url=~\"$base_url\",collection=~\"$collection\",shard=~\"$shard\",replica=~\"$replica\",core=~\"$core\"}[1m])",
     "legendFormat": "{{base_url}}/{{core}}"
    }
   ]
  },
  {
   "title": "Update Handler Merges",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 216 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(solr_metrics_core_update_handler_merges_total{base_url=~\"$base_url\",collection=~\"$collection\",shard=~\"$shard\",replica=~\"$replica\",core=~\"$core\"}[1m])",
     "legendFormat": "{{base_url}}/{{core}}"
    }
   ]
  },
  {
   "title": "Update Handler Splits",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 216 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(solr_metrics_core_update_handler_splits_total{base_url=~\"$base_url\",collection=~\"$collection\",shard=~\"$shard\",replica=~\"$replica\",core=~\"$core\"}[1m])",
     "legendFormat": "{{base_url}}/{{core}}"
    }
   ]
  },
  {
   "title": "Update Handler Optimizes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 223 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(solr_metrics_core_update_handler_optimizes_total{base_url=~\"$base_url\",collection=~\"$collection\",shard=~\"$shard\",replica=~\"$replica\",core=~\"$core\"}[1m])",
     "legendFormat": "{{base_url}}/{{core}}"
    }
   ]
  },
  {
   "title": "Update Handler Rollbacks",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 223 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(solr_metrics_core_update_handler_rollbacks_total{base_url=~\"$base_url\",collection=~\"$collection\",shard=~\"$shard\",replica=~\"$replica\",core=~\"$core\"}[1m])",
     "legendFormat": "{{base_url}}/{{core}}"
    }
   ]
  },
  {
   "title": "Update Handler Soft Auto Commits",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 230 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(solr_metrics_core_update_handler_soft_auto_commits_total{base_url=~\"$base_url\",collection=~\"$collection\",shard=~\"$shard\",replica=~\"$replica\",core=~\"$core\"}[1m])",
     "legendFormat": "{{base_url}}/{{core}}"
    }
   ]
  },
  {
   "title": "Update Handler Auto Commits",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 230 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(solr_metrics_core_update_handler_auto_commits_total{base_url=~\"$base_url\",collection=~\"$collection\",shard=~\"$shard\",replica=~\"$replica\",core=~\"$core\"}[1m])",
     "legendFormat": "{{base_url}}/{{core}}"
    }
   ]
  },
  {
   "title": "Update Handler Commits",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 230 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(solr_metrics_core_update_handler_commits_total{base_url=~\"$base_url\",collection=~\"$collection\",shard=~\"$shard\",replica=~\"$replica\",core=~\"$core\"}[1m])",
     "legendFormat": "{{base_url}}/{{core}}"
    }
   ]
  },
  {
   "title": "Update Handler Errors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 237 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(solr_metrics_core_update_handler_errors_total{base_url=~\"$base_url\",collection=~\"$collection\",shard=~\"$shard\",replica=~\"$replica\",core=~\"$core\"}[1m])",
     "legendFormat": "{{base_url}}/{{core}}"
    }
   ]
  }
 ]
}